services:
  postgres:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blub
      POSTGRES_PASSWORD: blub
      POSTGRES_DB: blub
    restart: unless-stopped
